config:
  install_tree: $INSTALL_DIR_PATH/install
  module_roots:
    tcl: $INSTALL_DIR_PATH/tcl
  build_stage:
    - $INSTALL_DIR_PATH/.stage/
  install_path_scheme: '${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH:8}'
