config:
  install_path_scheme: ${ARCHITECTURE}/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH:6}
  install_tree: ~/HBP/install/knl
  module_roots:
    tcl: ~/HBP/install/knl/tcl
    lmod: ~/HBP/install/knl/lmod
  build_stage:
    - $spack/var/spack/stage
