#!/bin/bash


# for stable branch we always build all packages
packages=(
        'mod2c'
        'coreneuron ~neurodamusmod ~report'
        'coreneuron ~neurodamusmod ~report ~mpi'
        'coreneuron ~neurodamusmod ~report ~openmp ~mpi'
        'neuron@develop +python ^python@3'
        'neuron@develop +python ^python@2.7'
        'neuron@develop ~python'
        'neuron@develop +shared ~mpi'
)


# module support
if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    source /etc/profile.d/modules.sh
else
    source /usr/local/opt/modules/Modules/init/bash
fi


# spack command line support
source $SPACK_ROOT/share/spack/setup-env.sh


# list the packages
echo " == > BUILDING ${#packages[*]} PACKAGES : "${packages[*]}""


# build all packages now
for package in "${packages[@]}"
do

    # to avoid large debug log and 4MB limit, redirect to file and delete later
    echo " == > PACKAGE SPEC : spack spec -I $package "
    spack spec -I $package

    # install package
    (spack install $package; exit 0)

    # check if package installed properly
    if [[ `spack find $package` == *"No package matches"* ]];  then

        echo " == > PACKAGE INSTALLATION CHECK FAILED, BUILD LOG : "
        cat `spack location $package`/spack-build.out
        exit 1

    fi
done


# show all generated modules
echo " == > AUTOGENERATED MODULES : module avail"
module avail


# show single module
echo " == > EXAMPLE OF MODULE : module show neuron"
module show neuron


# show packages will dependency dag
echo " == > INSTALLED PACKAGES (WITH DEPENDENCY DAG) : spack find -d -v"
spack find -d -v
